In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.5.0


In [ ]:
import numpy as np


In [ ]:
Basics of Tensors

In [ ]:
# indiexes ==> #accessing the  specific element in the data structure's using the index  access element 40
a = [10,20,30,40,50]


In [ ]:
a[3]

40

In [ ]:
#tensor 
dd =[
     [1,1,1],
     [2,2,2],
     [3,3,3],
]

In [ ]:
dd[0][2]

1

In [ ]:
print(len(dd))# length oof the list not the dimension or index of the list

3


In [ ]:
## Atttributes of Tensors
1.shape
2.rank 
3.axes


In [ ]:
# rank  ==> Rank of a tensor which  tells us the number of  dimensions of the with in the tensor 
# example here rk is the tensor
rk =[
     [1,2,3],
     [4,5,6],
     [7,8,9]
]


In [ ]:
rk[0]# rk[0]==> means rank[0] which means one dimensions

[1, 2, 3]

In [ ]:
rk[1]

[4, 5, 6]

In [ ]:
rk[2]

[7, 8, 9]

In [ ]:
rk[0][0]

1

In [ ]:
print(rk[0][1])
print(rk[0][2])
print(rk[0][0])

2
3
1


In [ ]:
#Axes ==>  An axes of tensor is a specific dimension of a tensor
#which means 
rk[0] # ==> this is first axis 

[1, 2, 3]

In [ ]:
print(rk[1])# ==> this is the second axis
print(rk[2]) #==> this is the third axis

[4, 5, 6]
[7, 8, 9]


In [ ]:
rk[0][2]# rk has a rank of 2
# rk has 0==> axis
# rk has 1==> index or  number

3

In [ ]:
#Rank of tensors tells us the how many axes that  tensors has  and the length of the axes will lead us to very umprortant concept as Shape

In [ ]:
#  Shape =>>
#Shape is determined by the length of the axis so if we know the shape of the given tensor then we know the length of the axes
#shape and size perform same functionalites but the names are diffrent


In [ ]:
# lets create a 2d array
rk =[
     [33,22,11],
     [66,55,44],
     [99,88,77]
]

In [ ]:
t = tf.constant(rk) # constant() ==> constant function that helps us to create the constant tensor
t.shape


TensorShape([3, 3])

In [ ]:
print(type(t))# tensor type

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[33, 22, 11],
       [66, 55, 44],
       [99, 88, 77]], dtype=int32)>

In [ ]:
Operations of Tensor
1.Reshaping Operations
2.Element wise Operations
3.Reduction Operations
4.Axes Operations

In [ ]:
# Reshpaping  Operaions of a  Tensor in Tensorflow
==> Shape
==> flaten
==> concat

In [ ]:
S = tf.constant([
                 [45,12,78],
                 [89,56,23],
                 [79,46,13],
                 [75,53,94]
],dtype =tf.int32)

In [ ]:
S.shape

TensorShape([4, 3])

In [ ]:
reshaped_tensor =tf.reshape(S, [2,6])
print(reshaped_tensor)

tf.Tensor(
[[45 12 78 89 56 23]
 [79 46 13 75 53 94]], shape=(2, 6), dtype=int32)


In [ ]:
reshaped_tensor =tf.reshape(S,[1,12])
print(reshaped_tensor)

tf.Tensor([[45 12 78 89 56 23 79 46 13 75 53 94]], shape=(1, 12), dtype=int32)


In [ ]:
reshaped_tensor=tf.reshape(S,[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[45, 12, 78],
       [89, 56, 23],
       [79, 46, 13],
       [75, 53, 94]], dtype=int32)>

In [ ]:
reshaped_tensor=tf.reshape(S,[3,4])
reshaped_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[45, 12, 78, 89],
       [56, 23, 79, 46],
       [13, 75, 53, 94]], dtype=int32)>

In [ ]:
reshaped_tensor=tf.reshape(S,[6,2])
reshaped_tensor

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[45, 12],
       [78, 89],
       [56, 23],
       [79, 46],
       [13, 75],
       [53, 94]], dtype=int32)>

In [ ]:
reshaped_tensor=tf.reshape(S,[12,1])
reshaped_tensor

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[45],
       [12],
       [78],
       [89],
       [56],
       [23],
       [79],
       [46],
       [13],
       [75],
       [53],
       [94]], dtype=int32)>

In [ ]:
reshaped_tensor=tf.reshape(S,[2,2,3])
reshaped_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[45, 12, 78],
        [89, 56, 23]],

       [[79, 46, 13],
        [75, 53, 94]]], dtype=int32)>

In [ ]:
## By  using the reshape() ==> which can specify the rows * cols shape that we are seeking.
# Notice how all of the shapes have to account for the number of elements in the tensor. 

In [ ]:
## Chane the shape by using the 
# Squeezing ==> A tensor removes the dimensions of the axes that have a length of one
# UnSqueezing ==> A tensor adds the dimensions of the axes that have a lenght of one


In [ ]:
print(tf.reshape(S,[1,12])),

tf.Tensor([[45 12 78 89 56 23 79 46 13 75 53 94]], shape=(1, 12), dtype=int32)


(None,)

In [ ]:
print(tf.reshape(S,[1,12]).shape)

(1, 12)


In [ ]:
print(tf.squeeze(tf.reshape(S,[1,12])))

tf.Tensor([45 12 78 89 56 23 79 46 13 75 53 94], shape=(12,), dtype=int32)


In [ ]:
print(tf.squeeze(tf.reshape(S,[1,12])).shape)

(12,)


In [ ]:
#Flatten a Tensor ==> A flatten a tensor means reshapes the tensor to have a shape that is equal to the number of elements contained in the tensor
#which means reshapeing the tensor with 1-d array 


In [ ]:
def flatten(S):
  S= tf.reshape(S,[1,-1])
  S= tf.squeeze(S)
  return S
flatten(S)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([45, 12, 78, 89, 56, 23, 79, 46, 13, 75, 53, 94], dtype=int32)>

In [ ]:
T=tf.ones([4,3])
T

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
flatten(T)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
Concatenating Tensors
# here we combine  two tensors by using the concat() function and the resulting fucntion will have a shape that depends on the  shape of the two input tensors


In [ ]:
tf1 =tf.constant([
                  [545,7890],
                  [852,369]])
tf2 =tf.constant([
                  [45,60],[23,56]
])
tf3 = tf.concat((tf1, tf2),axis=0)

In [ ]:
tf3.shape

TensorShape([4, 2])

In [ ]:
tf1.shape,tf2.shape

(TensorShape([2, 2]), TensorShape([2, 2]))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')