In [5]:
import tensorflow as tf
import numpy as np

In [3]:
print(tf.__version__)

2.5.0


In [28]:
rank3_tensor = tf.constant([[1,2,3,4],
                           [5,6,7,8],
                           [9,10,11,12],
                           [13,14,15,16]
                           ],dtype =tf.int32)

In [33]:
rank3_tensor[1][3] # here we  are refering to the elemet it rank3_tensor == 8

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
Conversion of Tensor to Numpy


In [35]:
a =tf.constant([
                [89,56,74],
                [1,2,3]
])
b= tf.constant([
                [45,56,12],
                [25,36,69]
])


In [44]:
np.array(a)
b.numpy()


array([[45, 56, 12],
       [25, 36, 69]], dtype=int32)

In [45]:
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[45, 56, 12],
       [25, 36, 69]], dtype=int32)>

In [46]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[89, 56, 74],
       [ 1,  2,  3]], dtype=int32)>

In [ ]:
Mathmatics Operations on Tensors


In [16]:
abc =tf.constant([
                  [1,2,3],
                  [2,2,2],
                  [1,1,1]
])
cde= tf.constant([
                  [1,1,1],
                  [1,1,1],
                  [1,1,1]
])

In [8]:
tf.add(abc ,cde )  ## by using add() we are able to add the two tensors 

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [3, 3, 3, 3]], dtype=int32)>

In [9]:
tf.multiply(abc,cde)# using the multiply ==> we are going to mulitiplicate the two tensors


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 2, 2, 2]], dtype=int32)>

In [17]:
print(tf.matmul(abc,cde)) # using matmul()  ==> we are going to perform matrix multiplication

tf.Tensor(
[[6 6 6]
 [6 6 6]
 [3 3 3]], shape=(3, 3), dtype=int32)


In [25]:
print("Type of every element:",abc.dtype)
print("Number of Dimensions:",abc.ndim)
print("Shape of a Tensor",abc.shape)
print("Elements along the axis 0 of the Tensor:",abc.shape[0])
print("Elements along the last axis  of the Tensor:",abc[-1])
print("Total no of elements(3*3):",tf.size(abc).numpy())

Type of every element: <dtype: 'int32'>
Number of Dimensions: 2
Shape of a Tensor (3, 3)
Elements along the axis 0 of the Tensor: 3
Elements along the last axis  of the Tensor: tf.Tensor([1 1 1], shape=(3,), dtype=int32)
Total no of elements(3*3): 9


In [31]:
rank_1tensor= tf.constant([0,1,2,3,69,45,5,45,96,78,45,63,12,36,89])
print((rank_1tensor).shape)
print(rank_1tensor)

(15,)
tf.Tensor([ 0  1  2  3 69 45  5 45 96 78 45 63 12 36 89], shape=(15,), dtype=int32)


In [34]:
print("First: ",rank_1tensor[0].numpy())
print("Second: ",rank_1tensor[1].numpy())
print("Last: ",rank_1tensor[-1].numpy())

First:  0
Second:  1
Last:  89


In [44]:
print("Everything: " ,rank_1tensor[:].numpy())
print("Before 4 :", rank_1tensor[0:11].numpy())
print("From 4 to End:", rank_1tensor[4:].numpy())
print("From 2 Before 7: ",rank_1tensor[1:8].numpy())
print("Reversed: ",rank_1tensor[::-1].numpy())

Everything:  [ 0  1  2  3 69 45  5 45 96 78 45 63 12 36 89]
Before 4 : [ 0  1  2  3 69 45  5 45 96 78 45]
From 4 to End: [69 45  5 45 96 78 45 63 12 36 89]
From 2 Before 7:  [ 1  2  3 69 45  5 45]
Reversed:  [89 36 12 63 45 78 96 45  5 45 69  3  2  1  0]


In [ ]:
Manipulating Shapes


In [47]:
var_x= tf.Variable(tf.constant([[45],[15],[35],[65],[25]]))
var_x.shape

TensorShape([5, 1])

In [50]:
print(var_x.shape.as_list())

[5, 1]


In [ ]:
#You Can a reshape a tensor into a new shape the tf.reshape operation is fasteset and cheap as the underlying data does not need to be duplicated

In [54]:
#here we can reshape a tensor to a new shape
# Note that we are repassing in a list
reshaped =tf.reshape(var_x,[1,5])
print(reshaped.numpy())

[[45 15 35 65 25]]


In [60]:
reshaped1= tf.reshape(var_x,[5,1])
print(reshaped1.numpy())

[[45]
 [15]
 [35]
 [65]
 [25]]


In [69]:
reshaped_neg =tf.reshape(rank_1tensor,[-1]) # the negitve shapes
print(reshaped_neg)

tf.Tensor([ 0  1  2  3 69 45  5 45 96 78 45 63 12 36 89], shape=(15,), dtype=int32)


In [ ]:
tf.reshape uses and exaples

In [72]:
#the  only resonable uses of ""tf.reshape()"" is to combine or to split the edges of axes or (add\remove by one),
#for this(3*2*5) tensor reshaaping to (3*2)*5) or (3*(2*5)) are both reasonable things to do  as the slics do not mix


In [70]:
tensor_reshape =tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
print(tensor_reshape)

tf.Tensor(
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30], shape=(30,), dtype=int32)


In [73]:
print(tf.reshape(tensor_reshape,[3,2,5]))

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]], shape=(3, 2, 5), dtype=int32)


In [74]:
print(tf.reshape(tensor_reshape,[2,3,5]))

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32)


In [76]:
print(tf.reshape(tensor_reshape,[5,6]))

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]], shape=(5, 6), dtype=int32)


In [77]:
print(tf.reshape(tensor_reshape,[6,5]))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]], shape=(6, 5), dtype=int32)


In [79]:
print(tf.reshape(tensor_reshape,[5,1,6]))

tf.Tensor(
[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]]

 [[19 20 21 22 23 24]]

 [[25 26 27 28 29 30]]], shape=(5, 1, 6), dtype=int32)


In [80]:
print(tf.reshape(tensor_reshape,[6,1,5]))

tf.Tensor(
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]

 [[16 17 18 19 20]]

 [[21 22 23 24 25]]

 [[26 27 28 29 30]]], shape=(6, 1, 5), dtype=int32)


In [84]:
# when ever we passe's the [ x,-1] number to shape it fits according to the multilple of previous one
print(tf.reshape(tensor_reshape,[3, -1]))
print(tf.reshape(tensor_reshape,[6, -1]))

tf.Tensor(
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]], shape=(3, 10), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]], shape=(6, 5), dtype=int32)


In [86]:
If you want to Reorder the Axes we need to use the ""tf.transpose"" not the ""tf.reshape()"" please do not use to change the axes using the tf.reshape() this was a Bas example